# Generated by Django 5.1.3 on 2024-12-02 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Categorie',
            new_name='Category',
        ),
    ]
