# Generated by Django 5.1.3 on 2024-12-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0002_rename_categorie_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Category',
            new_name='category',
        ),
    ]
